
import bnbIcon from '../../assets/chainicons/bnb.png';
import ethIcon from '../../assets/chainicons/ethereumlogo.png';
import polygonIcon from '../../assets/chainicons/polygon.png';
import arbitrumIcon from '../../assets/chainicons/arbitrum.png';
import zksyncIcon from '../../assets/chainicons/zksync.png';
import baseIcon from '../../assets/chainicons/basechain.png';
import optimismIcon from '../../assets/chainicons/op.png';

export const networks = [
  {
    name: 'BNB Smart Chain',
    slug: 'bsc',
    show: true,
    chainId: '0x38',
    networkVersion: '56',
    rpcUrl: 'https://bsc-dataseed.binance.org/',
    blockExplorerUrl: 'https://bscscan.com',
    symbol: 'BNB',
    decimals: 18,
    chainIcon: bnbIcon,
    localicon: true,
  },
  {
    name: 'Ethereum Mainnet',
    slug: 'eth',
    show: true,
    chainId: '0x1',
    networkVersion: '1',
    rpcUrl: 'https://rpc.ankr.com/eth',
    blockExplorerUrl: 'https://etherscan.io',
    symbol: 'ETH',
    decimals: 18,
    chainIcon: ethIcon,
    localicon: true,
  },
  {
    name: 'Polygon',
    slug: 'polygon',
    show: true,
    chainId: '0x89',
    networkVersion: '137',
    rpcUrl: 'https://polygon-rpc.com',
    blockExplorerUrl: 'https://polygonscan.com',
    symbol: 'MATIC',
    decimals: 18,
    chainIcon: polygonIcon,
    localicon: true,
  },
  {
    name: 'Arbitrum One',
    slug: 'arbitrum',
    show: true,
    chainId: '0xa4b1',
    networkVersion: '42161',
    rpcUrl: 'https://arb1.arbitrum.io/rpc',
    blockExplorerUrl: 'https://arbiscan.io',
    symbol: 'ARB',
    decimals: 18,
    chainIcon: arbitrumIcon,
    localicon: true,
  },
  {
    name: 'zkSync Era',
    slug: 'zksync',
    show: true,
    chainId: '0x144',
    networkVersion: '324',
    rpcUrl: 'https://mainnet.era.zksync.io',
    blockExplorerUrl: 'https://explorer.zksync.io',
    symbol: 'ETH',
    decimals: 18,
    chainIcon: zksyncIcon,
    localicon: true,
  },
  {
    name: 'Base',
    slug: 'base',
    show: true,
    chainId: '0x2105',
    networkVersion: '8453',
    rpcUrl: 'https://mainnet.base.org',
    blockExplorerUrl: 'https://basescan.org',
    symbol: 'ETH',
    decimals: 18,
    chainIcon: baseIcon,
    localicon: true,
  },
  {
    name: 'Optimism',
    slug: 'optimism',
    show: true,
    chainId: '0xa',
    networkVersion: '10',
    rpcUrl: 'https://mainnet.optimism.io',
    blockExplorerUrl: 'https://optimistic.etherscan.io',
    symbol: 'ETH',
    decimals: 18,
    chainIcon: optimismIcon,
    localicon: true,
  },
];

export const WalletAssets = [
  {
    chainId: '0x38',
    balance: '0',
    tokens: [],
    nfts: [],
    slug: 'bsc',
    rpcUrl: 'https://bsc-dataseed.binance.org/',
    blockExplorerUrl: 'https://bscscan.com',
    name: 'Binance Coin',
    symbol: 'BNB',
    decimals: 18,
    nativeCurrency: {
      name: 'Binance Coin',
      symbol: 'BNB',
      decimals: 18,
      address: '0x0000000000000000000000000000000000000000',
      slug: 'bsc',
    },
    show: true,
  },
  {
    chainId: '0x1',
    balance: '0',
    tokens: [],
    nfts: [],
    slug: 'eth',
    rpcUrl: 'https://rpc.ankr.com/eth',
    blockExplorerUrl: 'https://etherscan.io',
    name: 'Ethereum Mainnet',
    symbol: 'ETH',
    decimals: 18,
    nativeCurrency: {
      name: 'Ethereum Mainnet',
      symbol: 'ETH',
      decimals: 18,
      address: '0x0000000000000000000000000000000000000000',
      slug: 'eth',
    },
    show: true,
  },
  {
    chainId: '0x89',
      balance: '0',
      tokens: [],
      nfts: [],
      slug: 'polygon',
      rpcUrl: 'https://polygon-rpc.com',
      blockExplorerUrl: 'https://polygonscan.com',
      name: 'Polygon',
      symbol: 'MATIC',
      decimals: 18,
      nativeCurrency: {
        name: 'Polygon',
        symbol: 'MATIC',
        decimals: 18,
        address: '0x0000000000000000000000000000000000000000',
        slug: 'polygon',
      },
      show: true,
  }, 
  {
    chainId: '0xa4b1',
    balance: '0',
    tokens: [],
    nfts: [],
    slug: 'arbitrum',
    rpcUrl: 'https://arb1.arbitrum.io/rpc',
    blockExplorerUrl: 'https://arbiscan.io',
    name: 'Arbitrum One',
    symbol: 'ARB',
    decimals: 18,
    nativeCurrency: {
      name: 'Arbitrum One',
      symbol: 'ARB',
      decimals: 18,
      address: '0x0000000000000000000000000000000000000000',
      slug: 'arbitrum',
    },
    show: true,
  },
  {
    chainId: '0xa4b1',
    balance: '0',
    tokens: [],
    nfts: [],
    slug: 'zksync',
    rpcUrl: 'https://mainnet.era.zksync.io',
    blockExplorerUrl: 'https://explorer.zksync.io',
    name: 'zkSync Era',
    symbol: 'ETH',
    decimals: 18,
    nativeCurrency: {
      name: 'zkSync Era',
      symbol: 'ETH',
      decimals: 18,
      address: '0x0000000000000000000000000000000000000000',
      slug: 'zksync',
    },
    show: true,
  },
  {
    chainId: '0x2105',
    balance: '0',
    tokens: [],
    nfts: [],
    slug: 'base',
    rpcUrl: 'https://mainnet.base.org',
    blockExplorerUrl: 'https://basescan.org',
    name: 'Base',
    symbol: 'ETH',
    decimals: 18,
    nativeCurrency: {
      name: 'Base',
      symbol: 'ETH',
      decimals: 18,
      address: '0x0000000000000000000000000000000000000000',
      slug: 'base',
    },
    show: true,
  },
  {
    chainId: '0xa',
    balance: '0',
    tokens: [],
    nfts: [],
    slug: 'optimism',
    rpcUrl: 'https://mainnet.optimism.io',
    blockExplorerUrl: 'https://optimistic.etherscan.io',
    name: 'Optimism',
    symbol: 'ETH',
    decimals: 18,
    nativeCurrency: {
      name: 'Optimism',
      symbol: 'ETH',
      decimals: 18,
      address: '0x0000000000000000000000000000000000000000',
      slug: 'optimism',
    },
    show: true,
  },
]


export const all_chains_txns = {
  bsc: [],
  eth: [],
  polygon: [],
  arbitrum: [],
  zksync: [],
  base: [],
  optimum: [],
};


export const AllChainIds = ["0x38", "0x1", "0x89", "0xa4b1", '0x144', '0x2105', '0xa'];


