import { StatusBar, StyleSheet } from "react-native";
import {
    widthPercentageToDP as wp,
    heightPercentageToDP as hp,
  } from 'react-native-responsive-screen';

const styles = StyleSheet.create({
    container: {
      paddingHorizontal: wp('4%'),
      backgroundColor: 'white',
      paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight || hp('5%') : hp('5%'),
      paddingBottom: hp('3%'),
    },
    flatListSpacing: {
      paddingBottom: hp('1%'),
    },
    card: {
      width: wp('70%'),
      height: hp('20%'),
      borderRadius: wp('4%'),
      padding: wp('4%'),
      marginRight: wp('4%'),
      justifyContent: 'space-between',
    },
    addCard: {
      borderWidth: 1,
      borderColor: '#00C2AA',
      backgroundColor: '#fff',
    },
    accountLabel: {
      color: '#fff',
      fontSize: wp('4%'),
      fontWeight: '600',
    },
    address: {
      top: wp("1%"),
      color: '#fff',
      fontSize: wp('3.5%'),
    },
    balance: {
      fontSize: wp('6.5%'),
      color: '#fff',
      fontWeight: 'bold',
    },
    ethText: {
      color: '#fff',
      fontSize: wp('3.4%'),
    },
    iconRow: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      marginTop: hp('1%'),
    },
    icon: {
      marginLeft: wp('1%'),
    },
    tipText: {
      textAlign: 'center',
      fontWeight: '500',
      color: 'gray',
      marginVertical: hp('1.5%'),
    },
    actionRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: hp('2%'),
    },
    actionCard: {
      width: wp('44%'),
      borderWidth: 1,
      borderColor: '#eee',
      borderRadius: wp('3%'),
      padding: wp('3%'),
      alignItems: 'center',
      backgroundColor: 'white',
    },
    actionText: {
      fontWeight: '600',
      marginTop: hp('1%'),
      fontSize: wp('4%'),
    },
    subText: {
      fontSize: wp('3%'),
      color: 'gray',
      marginTop: hp('0.5%'),
      textAlign: 'center',
    },
    warningCard: {
      backgroundColor: '#fff',
      padding: wp('4%'),
      borderRadius: wp('3%'),
      borderWidth: 0.6,
      borderColor: '#ccc',
    },
    warningText: {
      color: '#000',
      fontWeight: '500',
      marginBottom: hp('0.5%'),
    },
    warningDesc: {
      color: '#ccc',
      marginBottom: hp('1.5%'),
    },
    backupButton: {
      alignSelf: 'flex-start',
      paddingHorizontal: wp('-1%'),
      paddingVertical: hp('1%'),
      borderRadius: wp('2%'),
      alignSelf: 'flex-start',
    },
    backupText: {
      color: '#00C2AA',
      fontWeight: '600',
      justifyContent: "flex-start",
      alignSelf: 'flex-start',
    },
    addTitle: {
      fontSize: wp('5%'),
      fontWeight: '700',
      color: '#00C2AA',
    },
    addSub: {
      fontSize: wp('3.4%'),
      color: 'gray',
      marginVertical: hp('1%'),
    },
    addBtn: {
      flexDirection: 'row',
      backgroundColor: '#00C2AA',
      paddingVertical: hp('1.2%'),
      justifyContent: 'center',
      borderRadius: wp('2%'),
      marginBottom: hp('1.5%'),
    },
    addBtnText: {
      color: 'white',
      fontWeight: '600',
      fontSize: wp('3.8%'),
      marginLeft: wp('2%'),
    },
    sectionContainer: {
      marginTop: 20,
      paddingHorizontal: wp('4%'),
    },
    sectionHeading: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#000',
      marginBottom: 10,
    },
    sectionItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 15,
      borderBottomWidth: 1,
      borderBottomColor: '#eee',
    },
    sectionIcon: {
      marginRight: 15,
      height: wp("4.4%"),
      width: wp("5%"),
    },
    sectionText: {
      fontSize: 16,
      color: '#000',
    },
    supportCard: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: '#ccc',
      borderRadius: 10,
      padding: 15,
      marginTop: 20,
      marginHorizontal: 0, // remove previous horizontal margin
      paddingHorizontal: wp('4%'), // add horizontal padding to match
    },
    supportImage: {
      width: 60,
      height: 60,
      resizeMode: 'contain',
      marginRight: 15,
    },
    supportTextContainer: {
      flex: 1,
    },
    supportTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#000',
    },
    supportSubtitle: {
      fontSize: 12,
      color: '#666',
      marginTop: 4,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      paddingHorizontal: 1,
      paddingTop: 20,
    },
    networkButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'white',
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 6,
    },
    networkIcon: {
      width: 20,
      height: 20,
      marginRight: 8,
    },
    networkText: {
      fontSize: 14,
      fontWeight: 'bold',
      color: '#000',
    },
    chevronIcon: {
      marginLeft: 5,
    },
    iconCircle: {
      borderRadius: 25,
      padding: 10,
    },
    dropdown: {
      backgroundColor: 'white',
      borderWidth: 1,
      borderColor: '#ccc',
      borderRadius: 8,
      marginTop: 1,
      width: 200,
      position: 'absolute',
      zIndex: 999,
      top: 45,
    },
    dropdownItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 8,
      paddingHorizontal: 10,
    },
    dropdownItemImage: {
      width: 24,
      height: 24,
      marginRight: 10,
    },
    dropdownItemText: {
      fontSize: 14,
      fontWeight: 'bold',
      color: '#000',
    },
    dropdownItemSubText: {
      fontSize: 11,
      color: '#666',
    },
    balanceRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    descriptionback: {
      color: '#444',
      fontSize: 14,
      textAlign: 'center',
      marginBottom: 10,
    },
    backupButtonback: {
      marginTop: 20,
      backgroundColor: '#00C2AA',
      paddingVertical: 12,
      paddingHorizontal: 25,
      borderRadius: 6,
    },
    backupButtonTextback: {
      color: 'white',
      fontWeight: 'bold',
      fontSize: 14,
    },
    contentback: {
      alignItems: 'flex-start',
      width: '100%',
    },
    headingback: {
      fontSize: 20,
      fontWeight: 'bold',
      marginTop: 20,
      marginBottom: 12,
      color: '#000',
      textAlign: 'left',
    },
    descriptionback: {
      color: '#444',
      fontSize: 14,
      textAlign: 'left',
      marginBottom: 10,
      width: '100%',
    },
    sheetContainercode: {
      alignItems: "flex-start",
      width: '100%',
    },
    headerTextcode: {
      fontSize: 20,
      fontWeight: 'bold',
      alignItems: "flex-start",
      marginBottom: 5,
      color: '#000',
    },
    subTextcode: {
      fontSize: 14,
      color: '#666',
      alignItems: "flex-start",
      marginBottom: 15,
    },
    recoveryBoxcode: {
      flexDirection: 'row',
      borderWidth: 1,
      borderColor: '#000',
      borderRadius: 8,
      padding: 15,
      width: '100%',
      justifyContent: 'space-between',
      marginBottom: 20,
    },
    columncode: {
      flex: 1,
    },
    wordTextcode: {
      fontSize: 16,
      color: '#000',
      marginBottom: 8,
    },
    backupButtoncode: {
      backgroundColor: '#00C2AA',
      paddingVertical: 12,
      paddingHorizontal: 25,
      borderRadius: 6,
    },
    backupButtonTextcode: {
      color: 'white',
      fontWeight: 'bold',
      fontSize: 14,
    },
    titlefinish: {
      fontSize: 20,
      fontWeight: 'bold',
      marginTop: 60,
      alignItems: "flex-start",
      color: '#000',
    },
    descriptionfinish: {
      alignItems: "flex-start",
      marginTop: 15,
      fontSize: 14,
      color: '#555',
      paddingHorizontal: 10,
    },
    doneButtonfinish: {
      marginTop: 30,
      backgroundColor: '#00C2AA',
      paddingVertical: 12,
      paddingHorizontal: 35,
      borderRadius: 8,
    },
    doneButtonTextfinish: {
      color: '#fff',
      fontWeight: 'bold',
      fontSize: 14,
    },
    sheetTitleaccount: {
      fontSize: 20,
      fontWeight: 'bold',
      marginBottom: 10,
      color: '#000',
      alignSelf: 'flex-start',
    },
    sheetLabelaccount: {
      fontSize: 16,
      alignSelf: 'flex-start',
      marginBottom: 5,
      color: '#333',
    },
    inputaccount: {
      width: '100%',
      borderWidth: 1,
      borderColor: '#ccc',
      borderRadius: 8,
      padding: 10,
      marginBottom: 20,
      color: '#000',
    },
    addButtonaccount: {
      width: '100%',
      paddingVertical: 12,
      borderRadius: 6,
      alignItems: 'center',
    },
    addButtonTextaccount: {
      color: '#fff',
      fontWeight: 'bold',
      fontSize: 14,
    },
    supportImagee: {
      width: 30,
      height: 30,
      resizeMode: 'contain',
      marginRight: 15,
      },
  
  });