import { StyleSheet } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

  const styles = StyleSheet.create({
    container: {
    paddingBottom: 30,
    backgroundColor: 'white',
    flex:1,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center', // center vertically
      paddingHorizontal: wp('3.4%'),
      paddingTop: hp('4.5%'),
    },
    networkButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 6,
    },
    networkIcon: {
    width: 20,
    height: 20,
    marginRight: 8,
    },
    networkText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#000',
    },
    networkSection: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    iconRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: wp('3%'), // use marginRight if gap not supported
    },
    walletHeading: {
      fontSize: wp('6%'),
      fontWeight: 'bold',
      color: '#000',
      paddingHorizontal: wp('5%'),
      marginTop: hp('2%'), // reduce to move it up
    },
    keypadContainer: {
      marginTop: hp('2%'),
      width: '96%',
      alignItems: 'center',
      paddingBottom: hp('3%'),
    },
    keypadRow: {
      flexDirection: 'row',
      justifyContent: 'space-evenly',
      width: '100%',
      marginBottom: hp('2%'),
    },
    keyButton: {
      width: wp('16%'),
      height: wp('16%'),
      borderRadius: wp('1%'),
      backgroundColor: '#f1f1f1',
      justifyContent: 'center',
      alignItems: 'center',
    },
    keyText: {
      fontSize: wp('6%'),
      fontWeight: '600',
      color: '#000',
    },
    chevronIcon: {
    marginLeft: 5,
    },
    iconCircle: {
    borderRadius: 25,
    padding: 10,
    },
    dropdown: {
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    marginTop: 1,
    width: 200,
    position: 'absolute',
    zIndex: 999,
    top: 45,
    },
    dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 10,
    },
    dropdownItemImage: {
    width: 24,
    height: 24,
    marginRight: 10,
    },
    dropdownItemText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#000',
    },
    dropdownItemSubText: {
    fontSize: 11,
    color: '#666',
    },
    startCard: {
    borderWidth: 2,
    borderColor: '#00C2AA',
    borderRadius: 10,
    margin: 20,
    padding: 25,
    },
    startTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#00C2AA',
    textAlign: 'left',
    marginBottom: 20,
    },
    createWalletButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#00C2AA',
    borderRadius: 8,
    paddingVertical: 14,
    width: '100%',
    marginBottom: 10,
    },
    createWalletButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 14,
    },
    importWalletButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    paddingVertical: 14,
    width: '100%',
    backgroundColor: 'white',
    },
    importWalletText: {
    color: '#000',
    fontWeight: '400',
    fontSize: 14,
    },
    sectionContainer: {
    marginHorizontal: 20,
    marginTop: 20,
    },
    sectionHeading: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000',
    marginBottom: 10,
    },
    sectionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    },
    sectionIcon: {
    marginRight: 15,
    },
    sectionText: {
    fontSize: 16,
    color: '#000',
    },
    supportCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 10,
    marginHorizontal: 20,
    marginTop: 20,
    padding: 15,
    },
    supportImage: {
    width: 60,
    height: 60,
    resizeMode: 'contain',
    marginRight: 15,
    },
    supportTextContainer: {
    flex: 1,
    },
    supportTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000',
    },
    supportSubtitle: {
    fontSize: 12,
    color: '#666',
    marginTop: 4,
    },
    modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.5)',
    },
    bottomSheet: {
    backgroundColor: 'white',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingHorizontal: 20,
    paddingTop: 20,
    maxHeight: '90%',
    },
    closeButton: {
    alignSelf: 'flex-end',
    padding: 10,
    },
    closeText: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#000',
    },
    iconImage: {
    width: 60,
    height: 60,
    alignSelf: 'center',
    marginBottom: 20,
    },
    title: {
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 8,
    },
    subtitle: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    marginBottom: 30,
    },
    tipBox: {
    flexDirection: 'row',
    marginBottom: 20,
    },
    tipNumber: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    },
    tipNumberText: {
    color: 'white',
    fontWeight: 'bold',
    },
    tipTitle: {
    fontWeight: 'bold',
    fontSize: 15,
    marginBottom: 4,
    },
    tipDesc: {
    fontSize: 13,
    color: '#444',
    },
    createWalletButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 14,
    },
    footerText: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    marginVertical: 20,
    },
    bottomCreateButton: {
    backgroundColor: '#00C2AA',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 20,
    },
    bottomCreateButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
    },
    modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.5)',
    },
    bottomSheet: {
    backgroundColor: 'white',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingHorizontal: 20,
    paddingTop: 20,
    maxHeight: '90%',
    },
    closeButton: {
    alignSelf: 'flex-end',
    marginBottom: 10,
    },
    title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 8,
    },
    subtitle: {
    fontSize: 14,
    color: '#666',
    marginBottom: 20,
    },
    tipBox: {
    flexDirection: 'row',
    marginBottom: 20,
    },
    tipNumber: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    },
    tipNumberText: {
    color: 'white',
    fontWeight: 'bold',
    },
    tipContent: {
    flex: 1,
    },
    tipTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 4,
    },
    tipSubtitle: {
    fontSize: 13,
    color: '#666',
    },
    footerText: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    marginVertical: 20,
    },
    bottomCreateButton: {
    backgroundColor: '#00C2AA',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 20,
    },
    bottomCreateButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
    },
    pinSheet: {
    backgroundColor: 'white',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 30,
    maxHeight: '90%',
    alignItems: 'center',
    },
    backButton: {
    alignSelf: 'flex-start',
    marginBottom: 20,
    },
    pinTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 10,
    },
    pins: {
    fontSize: 17,
    fontWeight: '500',
    marginBottom: 10,
    },
    pinSubtitle: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    marginBottom: 30,
    },
    pinDotsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 30,
    },
    pinDot: {
    width: 15,
    height: 15,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#000',
    marginHorizontal: 10,
    },
    helperText: {
    fontSize: 12,
    color: '#666',
    marginTop: 20,
    textAlign: 'center',
    marginBottom: 20,
    },
    numberPad: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 20,
    },
    numberKey: {
    width: 80,
    height: 60,
    margin: 5,
    borderRadius: 8,
    backgroundColor: '#f2f2f2',
    justifyContent: 'center',
    alignItems: 'center',
    },
    numberText: {
    fontSize: 22,
    fontWeight: 'bold',
    },
    modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.5)',
    },
    pinSheet: {
    backgroundColor: 'white',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 40,
    alignItems: 'center',
    },
    backButton: {
    alignSelf: 'flex-start',
    marginBottom: 20,
    },
    pinTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 8,
    },
    pinSubtitle: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    marginBottom: 20,
    },
    pinDotsContainer: {
    flexDirection: 'row',
    marginBottom: 60,
    marginTop: 60,
    justifyContent: 'center',
    },
    pinDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#000',
    marginHorizontal: 10,
    },
    numberPad: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    },
    numberKey: {
    width: 80,
    height: 60,
    margin: 6,
    borderRadius: 10,
    backgroundColor: '#f2f2f2',
    justifyContent: 'center',
    alignItems: 'center',
    },
    numberText: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#000',
    },
    modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.5)',
    },
    modalContent: {
    backgroundColor: 'white',
    padding: 25,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    alignItems: 'center',
    },
    modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 20,
    color: '#000',
    },
    modalSubtitle: {
    fontSize: 13,
    textAlign: 'center',
    color: '#666',
    marginBottom: 30,
    },
    createWalletButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 14,
    },
    crossButton: {
    position: 'absolute',
    top: 15,
    right: 15,
    zIndex: 1,
    },
    crossText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#000',
    },
    csheetCloseBtn: {
    alignSelf: 'flex-end',
    padding: 8,
    },
    csheetCloseText: {
    fontSize: 26,
    fontWeight: 'bold',
    },
    csheetImage: {
    width: 60,
    height: 60,
    alignSelf: 'flex-start',
    marginBottom: 20,
    },
    csheetHeading: {
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'left',
    marginBottom: 8,
    },
    csheetSubheading: {
    fontSize: 14,
    color: '#666',
    textAlign: 'left',
    marginBottom: 24,
    lineHeight: 20,
    },
    csheetTipContainer: {
    gap: 20,
    },
    csheetTipRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    },
    csheetTipCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 4,
    },
    csheetTipCircleText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 12,
    },
    csheetTipContent: {
    flex: 1,
    paddingLeft: 12,
    },
    csheetTipTitle: {
    fontWeight: 'bold',
    fontSize: 14,
    marginBottom: 4,
    },
    csheetTipText: {
    fontSize: 13,
    color: '#444',
    lineHeight: 18,
    },
    csheetButton: {
    backgroundColor: '#00C2AA',
    marginTop: 30,
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    },
    csheetButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 14,
    },
    safetyClose: {
    alignSelf: 'flex-end',
    },
    safetyCloseText: {
    fontSize: 26,
    fontWeight: 'bold',
    },
    safetyImage: {
    width: 60,
    height: 60,
    marginBottom: 20,
    },
    safetyTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'left',
    marginBottom: 8,
    },
    safetySubheading: {
    fontSize: 14,
    color: '#666',
    textAlign: 'left',
    marginBottom: 24,
    lineHeight: 20,
    },
    safetyTipBlock: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    marginBottom: 28,
    },
    safetyNumberCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    },
    safetyNumberText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 14,
    },
    safetyTipTextBlock: {
    alignItems: 'flex-start',
    },
    safetyTipTitle: {
    fontWeight: 'bold',
    fontSize: 15,
    color: '#000',
    marginBottom: 6,
    },
    safetyTipDescription: {
    fontSize: 13,
    color: '#444',
    lineHeight: 18,
    },
    safetyCTA: {
    backgroundColor: '#00C2AA',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 30,
    marginBottom: 20,
    height:"6%",
    width:"40%",
    },
    safetyCTAText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 12,
    },
    stepText: {
    fontSize: 16,
    marginBottom: 10,
    color: '#aaa',
    fontWeight: '500',
    },
    stepDone: {
    color: '#ccc',
    },
    stepActive: {
    color: '#000',
    fontWeight: 'bold',
    },
    cursor: {
    width: 10,
    height: 15,
    backgroundColor: '#00C2AA',
    marginTop: 10,
    marginBottom: 20,
    },
    button: {
    backgroundColor: '#00C2AA',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 10,
    },
    buttonText: {
    color: 'white',
    fontWeight: 'bold',
    },
    heading: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#000',
    },
    gasRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
    },
    gasLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    },
    gasText: {
    fontSize: 14,
    marginLeft: 6,
    color: '#000',
    },
    ethValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000',
    },
    subheading: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000',
    marginBottom: 10,
    },
    card: {
    backgroundColor: '#f5f5f5',
    padding: 12,
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    },
    cardTitle: {
    fontSize: 14,
    fontWeight: '400',
    color: '#000',
    },
    cardSub: {
    fontSize: 12,
    color: '#666',
    marginTop: 2,
    },
    cardRight: {
    alignItems: 'flex-end',
    },
    cardCost: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#000',
    },
    infoText: {
    fontSize: 12,
    color: '#555',
    marginTop: 10,
    marginBottom: 20,
    },
    buyButton: {
    backgroundColor: '#00C2AA',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 15,
    },
    buyText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 14,
    },
    footer: {
    fontSize: 12,
    color: '#00C2AA',
    textAlign: 'left',
    textDecorationLine: 'underline',
    },

    openSheetButton: {
      backgroundColor: '#4CAF50',
      padding: 10,
      borderRadius: 5,
    },
    openSheetButtonText: {
      color: 'white',
      fontSize: 16,
    },
    closeButton: {
      backgroundColor: 'transparent',
    },
    titleimport: {
      fontSize: 22,
      fontWeight: '400',
      textAlign: "left",
      marginTop: 40,
      marginBottom: 20,
      left:20,
    },
    optionContainer: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginBottom: 20,
      marginLeft: 10,
    },
    optionIcon: {
      marginRight: 10,
    },
    textContainer: {
      flex: 1,
      justifyContent: 'center',
    },
    optionText: {
      fontSize: 13,
      fontWeight: '400',
    },
    createText: {
      fontSize: 13,
      fontWeight: '600',
    },
    optionDescription: {
      fontSize: 14,
      color: '#666',
      marginTop: 5,
    },
    divider: {
      borderBottomWidth: 0.5,
      borderColor: '#ccc',
      marginVertical: 5,
      left: 40,
    },




    openSheetButtonn: {
      backgroundColor: '#4CAF50',
      padding: 10,
      borderRadius: 5,
    },
    openSheetButtonTextt: {
      color: 'white',
      fontSize: 16,
    },
    closeButtonContainerr: {
      position: 'absolute',
      top: 20,
      right: 20,
    },
    closeButtonn: {
      backgroundColor: 'transparent',
    },
    titlee: {
      fontSize: 22,
      fontWeight: 'bold',
      textAlign: 'center',
      marginTop: 40,
      marginBottom: 20,
    },
    descriptionn: {
      fontSize: 16,
      color: '#666',
      textAlign: 'center',
      marginBottom: 30,
    },
    continueButtonn: {
      backgroundColor: '#00C2AA',
      paddingVertical: 12,
      paddingHorizontal: 40,
      borderRadius: 8,
      alignSelf: 'center',
      marginTop: 20,
    },
    continueButtonTextt: {
      color: '#000',
      fontSize: 16,
    },
    inputPlaceholderr: {
      fontSize: 16,
      color: '#aaa',
      textAlign: 'center',
      marginBottom: 20,
    },

     openSheetButtonText: {
    color: 'white',
    fontSize: 16,
  },
  closeButtonContainer: {
    position: 'absolute',
    top: 20,
    right: 20,
  },
  closeButton: {
    backgroundColor: 'transparent',
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 40,
    marginBottom: 20,
  },
  description: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 30,
  },
  inputContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-evenly',
    marginBottom: 10,
  },
  inputBox: {
    width: '25%',
    marginBottom: 10,
    alignItems: 'center',
  },
  inputField: {
    width: '100%',
    height: 30,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    paddingLeft: 10,
    fontSize: 14,
  },
  continueButton: {
    backgroundColor: '#00C2AA',
    paddingVertical: 12,
    paddingHorizontal: 40,
    borderRadius: 8,
    alignSelf: 'center',
    marginTop: 20,
  },
  continueButtonText: {
    color: '#000',
    fontSize: 16,
    alignItems:"flex-end",
    justifyContent:"flex-end"
  },
  openSheetButton: {
    backgroundColor: '#4CAF50',
    padding: 10,
    borderRadius: 5,
  },
  openSheetButtonText: {
    color: 'white',
    fontSize: 16,
  },
  closeButtonContainer: {
    position: 'absolute',
    top: 20,
    right: 20,
    width: '100%', // Ensure the container takes the full width
    flexDirection: 'row',
    justifyContent: 'space-between', // Ensures close button is on the left and restore text is aligned to the end
    alignItems: 'center', // Centers the items vertically
    paddingHorizontal: 20,  // Added padding for better spacing
  },
  closeButton: {
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  restoreText: {
    color: '#000',
    fontSize: 16,
    textAlign: 'right', 
    flex: 1, 
    paddingRight: 10,  // Added padding for spacing between text and close icon
  },
  recovtitleContainer: {
    marginTop: 60,
    marginBottom: 20,
    alignItems: 'flex-start', // Align to the left
  },
  recovtitle: {
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'left',
  },
  description: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 30,
  },
  inputContainer: {
    flexDirection: 'column',
    flexWrap: 'wrap',
    justifyContent: 'space-evenly',
    marginBottom: 10,
  },
  inputBox: {
    marginBottom: 10,
    alignItems: 'center',
    width: '80%',
    marginVertical: 5,
  },
  inputField: {
    width: '100%',
    height: 40,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    paddingLeft: 10,
    fontSize: 14,
  },
  continueButton: {
    backgroundColor: '#00C2AA',
    paddingVertical: 12,
    paddingHorizontal: 40,
    borderRadius: 8,
    alignSelf: 'left',
    marginTop: 20,
  },
  continueButtonText: {
    color: '#000',
    fontSize: 16,
  },


  closeButtonContainerone: {
    position: 'absolute',
    top: 20,
    right: 20,
  },
  closeButtonone: {
    backgroundColor: 'transparent',
  },
  titleone: {
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 40,
    marginBottom: 20,
  },
  descriptionone: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 30,
  },
  createButtonone: {
    backgroundColor: '#00C2AA',
    paddingVertical: 12,
    paddingHorizontal: 40,
    borderRadius: 8,
    alignSelf: 'center',
    marginTop: 20,
  },
  createButtonTextone: {
    color: 'white',
    fontSize: 16,
  },
  
    });
  export default styles